# Generated by Django 5.0 on 2025-01-31 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_propiedades_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedades',
            name='estado',
            field=models.CharField(blank=True, max_length=69, null=True),
        ),
    ]
