# Generated by Django 5.0 on 2025-02-01 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_propiedades_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='administrador',
        ),
        migrations.RemoveField(
            model_name='propiedades',
            name='Numero_Inscripcion',
        ),
        migrations.RemoveField(
            model_name='propiedades',
            name='fecha_inscripcion',
        ),
        migrations.RemoveField(
            model_name='propiedades',
            name='fecha_resolucion',
        ),
        migrations.RemoveField(
            model_name='propiedades',
            name='nombre_canton',
        ),
        migrations.RemoveField(
            model_name='propiedades',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='propiedades',
            name='oficina_guarda_original',
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('fecha_inscripcion', models.DateField()),
                ('Numero_Inscripcion', models.IntegerField()),
                ('oficina_guarda_original', models.CharField(max_length=255)),
                ('nombre_canton', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_resolucion', models.DateField()),
                ('administrador', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Compra',
        ),
        migrations.DeleteModel(
            name='Propiedad',
        ),
    ]
