# Generated by Django 5.0 on 2025-02-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_propiedad_administrador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedades',
            name='codigo_interno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
