# Generated by Django 5.0 on 2025-02-01 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_registro_propiedad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro', models.CharField(max_length=255)),
                ('acto', models.CharField(max_length=255)),
                ('numero_Inscripcion', models.IntegerField()),
                ('fecha_inscripcion', models.DateField()),
                ('folio_inicial', models.CharField(max_length=255)),
                ('registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.registro')),
            ],
        ),
    ]
