# Generated by Django 5.0 on 2025-02-01 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_movimientos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientos',
            name='registro',
        ),
        migrations.AddField(
            model_name='movimientos',
            name='Propiedad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.propiedades'),
        ),
    ]
