# Generated by Django 5.0 on 2025-02-01 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_movimientos_registro_movimientos_propiedad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='propiedad',
        ),
        migrations.AddField(
            model_name='registro',
            name='solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.solicitante'),
        ),
    ]
