# Generated by Django 5.0 on 2025-02-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_solicitante_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedades',
            name='archivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
