# Generated by Django 5.0 on 2025-02-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_propiedades_archivo_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedades',
            name='documento_pdf',
            field=models.FileField(blank=True, null=True, upload_to='documento/'),
        ),
    ]
